domain: cn.ubuntu.com

image: prod-comms.ps5.docker-registry.canonical.com/cn.ubuntu.com

env:
  - name: SENTRY_DSN
    value: https://06096678a069442f9e6f72aa985f15ca@sentry.is.canonical.com//32

  - name: DISCOURSE_API_KEY
    secretKeyRef:
      key: ubuntu-api-key
      name: discourse-api

  - name: DISCOURSE_API_USERNAME
    secretKeyRef:
      key: ubuntu-api-username
      name: discourse-api

useProxy: false

readinessPath: "/_status/ping"

extraHosts:
  - domain: ubuntu-china.cn
    useParentTLS: True

# Overrides for production
production:
  replicas: 5
  nginxConfigurationSnippet: |
    if ($host != 'cn.ubuntu.com' ) {
      rewrite ^ https://cn.ubuntu.com$request_uri? permanent;
    }
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";

# Overrides for staging
staging:
  replicas: 3
  nginxConfigurationSnippet: |
    more_set_headers "X-Robots-Tag: noindex";
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";
